### PR TITLE
feature(backdrop): hide show backdrop method

### PR DESCRIPTION
**Pull request by thenaim**

### CODE REVIEW

**Comment by roman-rr** [comment]
@thenaim Thank you, scheduled.

**Comment by roman-rr** [comment]
Hello @thenaim 
Please describe a case where you will use manual backdrop hide/show methods.

**Comment by thenaim** [comment]
Hello @roman-rr,
For example, yoy can call a component and at the same time work with the main content of the application.

[Example 1](https://i.pinimg.com/originals/42/99/b5/4299b5a5217592285337132c05e68fac.jpg)
[Example 2](https://techcrunch.com/wp-content/uploads/2019/04/Tesla-app.png?w=730&crop=1)

**Comment by roman-rr** [comment]
@thenaim have you try `backdrop: false` in settings ? aren't cover your tasks ?

**Comment by thenaim** [comment]
Yes it works. But how to change dynamically, so I think it would be nice to make the present/dismiss methods.

**Pull request closed without merging**
